#pragma once

#include "NativeGameplayTags.h"

/** Input Action Tags */
// Tags used to bind abilities to input actions
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_ATTACK); // Primary attack input
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_ATTACK_ALT); // Alternate/secondary attack
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_ABILITY_1); // Ability slot 1
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_ABILITY_2); // Ability slot 2
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_ABILITY_3); // Ability slot 3
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_ABILITY_4); // Ability slot 4
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_ULTIMATE); // Ultimate ability
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_INTERACT); // Interact with world
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_DODGE); // Dodge/roll
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_BLOCK); // Block/shield
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INPUT_ACTION_CONSUMABLE); // Use consumable item
