#include "MythicTags_MetaProgression.h"


UE_DEFINE_GAMEPLAY_TAG(STAT_KILL_GENERIC, "Stat.Kill.Generic")
UE_DEFINE_GAMEPLAY_TAG(STAT_KILL_BOSS, "Stat.Kill.Boss")

UE_DEFINE_GAMEPLAY_TAG(STAT_DEATH, "Stat.Death")

UE_DEFINE_GAMEPLAY_TAG(STAT_ITEM_GATHERED, "Stat.Item.Gathered")
UE_DEFINE_GAMEPLAY_TAG(STAT_ITEM_LOOTED, "Stat.Item.Looted")
UE_DEFINE_GAMEPLAY_TAG(STAT_ITEM_CRAFTED, "Stat.Item.Crafted")

UE_DEFINE_GAMEPLAY_TAG(STAT_GOLD_EARNED, "Stat.Gold.Earned")

UE_DEFINE_GAMEPLAY_TAG(STAT_DISCOVERY, "Stat.Discovery")

UE_DEFINE_GAMEPLAY_TAG(STAT_QUEST_COMPLETED, "Stat.Quest.Completed")

UE_DEFINE_GAMEPLAY_TAG(STAT_DISTANCE_TRAVELED, "Stat.Distance.Traveled")

UE_DEFINE_GAMEPLAY_TAG(STAT_DEED_MERCY, "Stat.Deed.Mercy")
UE_DEFINE_GAMEPLAY_TAG(STAT_DEED_VIOLENCE, "Stat.Deed.Violence")

UE_DEFINE_GAMEPLAY_TAG(ACHIEVEMENT_SLAYER, "Achievement.Slayer")
UE_DEFINE_GAMEPLAY_TAG(ACHIEVEMENT_BOSS_HUNTER, "Achievement.BossHunter")

UE_DEFINE_GAMEPLAY_TAG(UNLOCK_RULE_SAMPLE, "Unlock.Rule.Sample")

UE_DEFINE_GAMEPLAY_TAG(TITLE_SLAYER, "Title.Slayer")
UE_DEFINE_GAMEPLAY_TAG(TITLE_BOSS_HUNTER, "Title.BossHunter")

UE_DEFINE_GAMEPLAY_TAG(RENOWN_SCOPE_GLOBAL, "Renown.Scope.Global")

UE_DEFINE_GAMEPLAY_TAG(RENOWN_GLOBAL_HATED, "Renown.Global.Hated")
UE_DEFINE_GAMEPLAY_TAG(RENOWN_GLOBAL_HOSTILE, "Renown.Global.Hostile")
UE_DEFINE_GAMEPLAY_TAG(RENOWN_GLOBAL_UNFRIENDLY, "Renown.Global.Unfriendly")
UE_DEFINE_GAMEPLAY_TAG(RENOWN_GLOBAL_NEUTRAL, "Renown.Global.Neutral")
UE_DEFINE_GAMEPLAY_TAG(RENOWN_GLOBAL_FRIENDLY, "Renown.Global.Friendly")
UE_DEFINE_GAMEPLAY_TAG(RENOWN_GLOBAL_HONORED, "Renown.Global.Honored")
UE_DEFINE_GAMEPLAY_TAG(RENOWN_GLOBAL_REVERED, "Renown.Global.Revered")
UE_DEFINE_GAMEPLAY_TAG(RENOWN_GLOBAL_EXALTED, "Renown.Global.Exalted")

UE_DEFINE_GAMEPLAY_TAG(PARAGON_NODE_VITALITY, "Paragon.Node.Vitality")
UE_DEFINE_GAMEPLAY_TAG(PARAGON_NODE_POWER, "Paragon.Node.Power")

UE_DEFINE_GAMEPLAY_TAG(TITLE_EXALTED, "Title.Exalted")
