#pragma once
#include "NativeGameplayTags.h"

/**World.Resource*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WORLD_RESOURCE_TREE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WORLD_RESOURCE_STONE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WORLD_RESOURCE_DRAGONSTONE)