#include "MythicTags_World.h"

UE_DEFINE_GAMEPLAY_TAG(WORLD_RESOURCE_TREE, "World.Resource.Tree")
UE_DEFINE_GAMEPLAY_TAG(WORLD_RESOURCE_STONE, "World.Resource.Stone")
UE_DEFINE_GAMEPLAY_TAG(WORLD_RESOURCE_DRAGONSTONE, "World.Resource.Dragonstone")

UE_DEFINE_GAMEPLAY_TAG(WORLD_EVENT_SEASON_SPRING, "World.Event.Season.Spring")
UE_DEFINE_GAMEPLAY_TAG(WORLD_EVENT_SEASON_SUMMER, "World.Event.Season.Summer")
UE_DEFINE_GAMEPLAY_TAG(WORLD_EVENT_SEASON_AUTUMN, "World.Event.Season.Autumn")
UE_DEFINE_GAMEPLAY_TAG(WORLD_EVENT_SEASON_WINTER, "World.Event.Season.Winter")