#pragma once
#include "NativeGameplayTags.h"

/**World.Resource*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WORLD_RESOURCE_TREE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WORLD_RESOURCE_STONE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WORLD_RESOURCE_DRAGONSTONE)

/** World.Event.Season.* — used as the EventTag of the World Chronicle beat posted when the calendar season turns
 *  (the chronicle distills these to "Season Spring/Summer/Autumn/Winter"). One per ESeason. */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WORLD_EVENT_SEASON_SPRING)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WORLD_EVENT_SEASON_SUMMER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WORLD_EVENT_SEASON_AUTUMN)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(WORLD_EVENT_SEASON_WINTER)