name: Issue
description: Create a new issue.
title: ""
labels: []
projects: ["416rehman/projects/8"]
body:
  - type: textarea
    id: comment
    attributes:
      label: Add a comment
      placeholder: Add your comment here
    validations:
      required: true
