#include "MythicTags_Inventory.h"

UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_DEFAULT, "Inventory.Slot.Default");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_EQUIPMENT, "Inventory.Slot.Equipment");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_ACCESSORY, "Inventory.Slot.Accessory");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_HOTBAR, "Inventory.Slot.Hotbar");
/*Itemization.Type*/
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_OTHER, "Itemization.Type.Other");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_EQUIPMENT, "Itemization.Type.Equipment");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_FOOD, "Itemization.Type.Food");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_RESOURCE, "Itemization.Type.Resource");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_WEAPON, "Itemization.Type.Weapon");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_PLAN, "Itemization.Type.Plan");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_SCROLL, "Itemization.Type.Scroll");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_SPECIAL, "Itemization.Type.Special");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_ACCESSORY, "Itemization.Type.Accessory");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_PLACABLE, "Itemization.Type.Placable");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_TOOL, "Itemization.Type.Tool");
/*Itemization.Rarity*/
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_RARITY_COMMON, "Itemization.Rarity.Common");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_RARITY_RARE, "Itemization.Rarity.Rare");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_RARITY_EPIC, "Itemization.Rarity.Epic");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_RARITY_LEGENDARY, "Itemization.Rarity.Legendary");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_RARITY_EXOTIC, "Itemization.Rarity.Exotic");
/*Itemization.ActionType*/
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_ACTIONTYPE_INHAND, "Itemization.ActionType.InHand");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_ACTIONTYPE_INHAND_BEGIN, "Itemization.ActionType.InHand.Begin");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_ACTIONTYPE_INHAND_END, "Itemization.ActionType.InHand.End");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_ACTIONTYPE_ININVENTORY, "Itemization.ActionType.InInventory");