#pragma once
#include "NativeGameplayTags.h"

/**Inventory.Slot*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_DEFAULT);	// Generic slot, can contain any item
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_EQUIPMENT);	// EQUIPMENT slot, can contain equipment items
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_ACCESSORY);	// ACCESSORY slot, can contain accessory items
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_HOTBAR);	// HOTBAR slot, can contain any item

/*ITEMIZATION.Type*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_OTHER);	// OTHER
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_EQUIPMENT);	// EQUIPMENT, can be equipped in the equipment slot
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_FOOD);	// can be consumed for a buff 
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_RESOURCE);	// can be used to craft other items
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_WEAPON);	// can be equipped in the equipment slot
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_PLAN);	// can be used to craft other items
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_SCROLL);	// can be used to learn a spell
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_SPECIAL);	// any special item
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_ACCESSORY);	// can be equipped in the accessory slot
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_PLACABLE); // can be placed in the world, i.e a box, crafting station, etc.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_TOOL);	// tools such as pickaxes, axes, shovels, etc.
/*ITEMIZATION.RARITY*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_RARITY_COMMON);	// COMMON
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_RARITY_RARE);	// RARE
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_RARITY_EPIC);	// EPIC
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_RARITY_LEGENDARY);	// LEGENDARY
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_RARITY_EXOTIC);	// EXOTIC
/**ITEMIZATION.ActionType*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_ACTIONTYPE_INHAND);	// The item can be used while in hand
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_ACTIONTYPE_ININVENTORY);	// The item can be used from the inventory UI