#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Damage_Hit);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Combat_KillConfirm);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Combat_Crit);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Combat_Reaction);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Combat_Resisted);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Combat_Immune);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Status_Burn_Onset);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Status_Bleed_Onset);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Status_Poison_Onset);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Status_Slow_Onset);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Status_Freeze_Onset);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Status_Stun_Onset);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Status_Weaken_Onset);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Status_Terrify_Onset);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_World_POIDiscovered);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_World_TreasureUnearthed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_World_FastTravel_Depart);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_World_FastTravel_Arrive);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_World_EnteringDanger);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Mount_TameSuccess);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Mount_Summon);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Necro_Raise);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Affix_Proc);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Reaction_Combo_Assist);
