
#pragma once

#include "CoreMinimal.h"
#include "RewardBase.h"
#include "Itemization/Inventory/MythicInventoryComponent.h"
#include "ItemReward.generated.h"

class IInventoryProviderInterface;

USTRUCT(BlueprintType, Blueprintable)
struct FItemRewardContext : public FRewardContext {
    GENERATED_BODY()

    /** Item level used for generation; zero resolves to the receiving player's Combat level. */
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    int32 ItemLevel = 0;

    /** Whether a world drop is visible and interactable only for the receiving player. */
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    bool bIsPrivate = true;

    /**
     * Optional destination inventory provider. Without one, the item becomes a world drop; if insertion fails, it
     * drops at the inventory owner's location.
     */
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TScriptInterface<IInventoryProviderInterface> InventoryProvider = nullptr;

    /** World-drop location used only when no inventory provider is supplied; zero resolves to the player's location. */
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FVector SpawnLocation = FVector::ZeroVector;
};

UCLASS(BlueprintType, Blueprintable)
class MYTHIC_API UItemReward : public URewardBase {
    GENERATED_BODY()

public:
    virtual bool Give(FRewardContext &Context) const override;

    virtual FText GetPreviewText() const override;

    /** Number of copies or stack units granted by this reward. */
    UPROPERTY(BlueprintReadWrite, EditAnywhere)
    int32 Quantity = 1;

    /** Canonical item definition generated by this reward. */
    UPROPERTY(BlueprintReadWrite, EditAnywhere)
    TObjectPtr<UItemDefinition> Item;

    /** Whether a successful grant notifies the owning client to play its reward celebration presentation. */
    UPROPERTY(BlueprintReadWrite, EditAnywhere)
    bool bCelebrate = true;

    /** Grants Reward using Context, inserting into its inventory provider or creating a private/shared world drop. */
    UFUNCTION(BlueprintCallable)
    static bool GiveItemReward(UItemReward *Reward, FItemRewardContext Context);

private:
    void NotifyCelebration(APlayerController *PC) const;
};
