// Mythic Living World — Native Gameplay Tags
// Central tag declarations for the Living World system.
// All event and category tags used by settlements, causal fabric, and simulation.

#pragma once
#include "NativeGameplayTags.h"

// ─── Event Tags (Causal Fabric) ──────────────────────────────
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_EVENT_TERRITORY_SETTLEMENT_TRANSFER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_EVENT_FACTION_SCHISM)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_EVENT_FACTION_ANNIHILATION)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_EVENT_FACTION_EVOLUTION)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_EVENT_FACTION_DEVOLUTION)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_EVENT_DIPLOMACY_SHIFT)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_EVENT_FACTION_ABSORPTION)
