// Mythic Living World — Native Gameplay Tag Definitions

#include "World/LivingWorld/MythicTags_LivingWorld.h"

// ─── Event Tags (Causal Fabric) ──────────────────────────────
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_EVENT_TERRITORY_SETTLEMENT_TRANSFER, "LivingWorld.Event.Territory.SettlementTransfer")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_EVENT_FACTION_SCHISM, "LivingWorld.Event.Faction.Schism")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_EVENT_FACTION_ANNIHILATION, "LivingWorld.Event.Faction.Annihilation")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_EVENT_FACTION_EVOLUTION, "LivingWorld.Event.Faction.Evolution")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_EVENT_FACTION_DEVOLUTION, "LivingWorld.Event.Faction.Devolution")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_EVENT_DIPLOMACY_SHIFT, "LivingWorld.Event.Diplomacy.Shift")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_EVENT_FACTION_ABSORPTION, "LivingWorld.Event.Faction.Absorption")

// ─── Action Tags (Moral Evaluation & Crime Pipeline) ─────────
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_VIOLENCE_ATTACK, "LivingWorld.Action.Violence.Attack")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_VIOLENCE_KILL, "LivingWorld.Action.Violence.Kill")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_THEFT_STEAL, "LivingWorld.Action.Theft.Steal")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_THEFT_SMUGGLE, "LivingWorld.Action.Theft.Smuggle")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_PROPERTY_TRESPASS, "LivingWorld.Action.Property.Trespass")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_MERCY_HEAL, "LivingWorld.Action.Mercy.Heal")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_MERCY_TEND, "LivingWorld.Action.Mercy.Tend")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_MAGIC_CAST, "LivingWorld.Action.Magic.Cast")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_MAGIC_FORBIDDEN, "LivingWorld.Action.Magic.Forbidden")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_AUTHORITY_ENFORCE, "LivingWorld.Action.Authority.Enforce")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_AUTHORITY_REPORT, "LivingWorld.Action.Authority.Report")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_SOCIAL_RALLY, "LivingWorld.Action.Social.Rally")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_SOCIAL_FLEE, "LivingWorld.Action.Social.Flee")
UE_DEFINE_GAMEPLAY_TAG(TAG_LIVINGWORLD_ACTION_SOCIAL_SUBMIT, "LivingWorld.Action.Social.Submit")
