// Mythic Living World — Native Gameplay Tags
// Central tag declarations for the Living World system.
// All event and category tags used by settlements, causal fabric, and simulation.

#pragma once
#include "NativeGameplayTags.h"

// ─── Event Tags (Causal Fabric) ──────────────────────────────
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_TERRITORY_SETTLEMENT_TRANSFER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_FACTION_SCHISM)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_FACTION_RESISTANCE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_FACTION_RESTORATION)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_FACTION_ANNIHILATION)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_FACTION_EVOLUTION)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_FACTION_DEVOLUTION)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_FACTION_FAMINE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_FACTION_WEAKNESS)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_DIPLOMACY_SHIFT)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_FACTION_ABSORPTION)
// Permanent (perma-death) death event — witnessed by the PressureProcessor / persistence layer.
// String uses the "World.Event.*" namespace (mirrors the "World.*"-prefixed TAG_WORLD_ACTION_BETRAYAL precedent).
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WORLD_EVENT_DEATH_PERMANENT)

// ─── Action Tags (Moral Evaluation & Crime Pipeline) ─────────
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_VIOLENCE_ATTACK)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_VIOLENCE_KILL)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_THEFT_STEAL)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_THEFT_SMUGGLE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_PROPERTY_TRESPASS)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_MERCY_HEAL)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_MERCY_TEND)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WORLD_ACTION_BETRAYAL)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_MAGIC_CAST)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_MAGIC_FORBIDDEN)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_AUTHORITY_ENFORCE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_AUTHORITY_REPORT)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_SOCIAL_RALLY)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_SOCIAL_FLEE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ACTION_SOCIAL_SUBMIT)

// ─── Phase 5 Tags (Cognitive, Party, Encounters, Schemes) ────
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_SCHEME_COMPLETED)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_SCHEME_DISCOVERED)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_ENCOUNTER_SPAWNED)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_ENCOUNTER_COMPLETED)
// Player-victory close (every spawned member dead) vs the generic COMPLETED (timed out / withdrew / force-completed).
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_ENCOUNTER_DEFEATED)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_COMPANION_JOINED)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_COMPANION_DEPARTED)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_COMPANION_BETRAYED)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EVENT_COGNITIVE_INTENTION_CHANGED)

// ─── Phase 6 Tags (Behavioral Responses & Emotions) ──────────
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EMOTION_JOY)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EMOTION_DESPAIR)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EMOTION_FEAR)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_EMOTION_GRIEF)

// ─── NPC Role Tags (Dynamic-Population — role-from-context) ───
// Stamped on FMythicIdentityFragment.RoleTag at spawn by the population/territory/traveler spawners.
// Leaf names deliberately preserve the substrings Guard/Soldier/Merchant so NPCGenerator::GeneratePersonality's
// RoleName.Contains() modifiers (NPCGenerator.cpp:267-285) fire unchanged on promotion. Single owner of this family.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_CIVILIAN)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_FARMER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_MERCHANT)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_LABORER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_FISHER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_GUARD)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_SOLDIER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_TRAVELER)
// Archetype catalog roles (sim-driven WHO spawns) — wealth/poverty-shaped urban archetypes. Noble is group-only.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_BEGGAR)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_SOCIALITE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_NOBLE)
// Hostile-camp occupant role (Step 3) — stamped on every NPC the population spawner fills into a bIsHostileCamp
// settlement's Enemy spawn points. Leaf name "Bandit" carries no GeneratePersonality substring modifier (it's neither
// Guard/Soldier/Merchant), so it falls through to the neutral personality path — intended for a generic hostile.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ROLE_BANDIT)

// ─── NPC Group Activity Tags (clustered spawning, Step 4) ────
// GroupTag of a code-default / authored FMythicGroupTemplate, also stamped on each member's FMythicGroupFragment.ActivityTag
// so the debugger can tally a group's kind. NPC.Group.Activity is the parent (the FMythicGroupTemplate.GroupTag UPROPERTY
// uses Categories="NPC.Group"). Single owner of this family.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_GROUP_ACTIVITY)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_GROUP_RETINUE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_GROUP_BARTER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_GROUP_SOCIAL)

// ─── NPC Activity Tags (context-driven activity catalog, Step 3) ──
// ActivityTag of a code-default / authored FMythicActivityDef. NPC.Activity is the parent (the FMythicActivityDef.ActivityTag
// UPROPERTY uses Categories="NPC.Activity"). Handed to the cosmetic OnPerformActivity BP hook + read by the debugger.
// Single owner of this family.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ACTIVITY)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ACTIVITY_FISH)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ACTIVITY_BARTER)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ACTIVITY_WORK)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ACTIVITY_REST)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ACTIVITY_SOCIALIZE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ACTIVITY_PATROL)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_ACTIVITY_WANDER)

// ─── Encounter Type Tags (EncounterDirector code-default templates) ──
// EncounterTag for the built-in code-default encounter templates (MythicEncounterDefaults::BuildDefaultTemplates).
// Distinct family from the LivingWorld.Event.Encounter.* LIFECYCLE beats (Spawned/Completed/Defeated) above — these
// identify the TEMPLATE KIND, the lifecycle tags mark the chronicle beat. An authored EncounterTemplateDatabase may
// reuse these tags (they're registered natively) or define its own; the director keys cooldown/instance-cap on whatever
// EncounterTag a template carries, so authored and code-default tags never collide.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ENCOUNTER_BANDIT_AMBUSH)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ENCOUNTER_PATROL)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ENCOUNTER_RAID)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_LIVINGWORLD_ENCOUNTER_WILDLIFE)
