#include "Interaction/ContextActions/MythicTags_ContextActions.h"

UE_DEFINE_GAMEPLAY_TAG(CONTEXT_ACTION_ROOT, "Context.Action");
UE_DEFINE_GAMEPLAY_TAG(CONTEXT_ACTION_REASON_ROOT, "Context.Action.Reason");
UE_DEFINE_GAMEPLAY_TAG(CONTEXT_ACTION_INPUT_ROOT, "UI.Action");
UE_DEFINE_GAMEPLAY_TAG(CONTEXT_ACTION_REASON_INVALID_TARGET, "Context.Action.Reason.InvalidTarget");
UE_DEFINE_GAMEPLAY_TAG(CONTEXT_ACTION_REASON_STALE, "Context.Action.Reason.Stale");
UE_DEFINE_GAMEPLAY_TAG(CONTEXT_ACTION_REASON_OUT_OF_RANGE, "Context.Action.Reason.OutOfRange");
UE_DEFINE_GAMEPLAY_TAG(CONTEXT_ACTION_REASON_OBSTRUCTED, "Context.Action.Reason.Obstructed");
UE_DEFINE_GAMEPLAY_TAG(CONTEXT_ACTION_REASON_NOT_FOCUSED, "Context.Action.Reason.NotFocused");
UE_DEFINE_GAMEPLAY_TAG(CONTEXT_ACTION_REASON_UNAVAILABLE, "Context.Action.Reason.Unavailable");
