#pragma once
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Weather);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Weather_Clear);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Weather_Overcast);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Weather_Rain);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Weather_Snow);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Time);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Time_Morning);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Time_Afternoon);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Time_Evening);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Time_Night);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Season);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Season_Spring);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Season_Summer);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Season_Autumn);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Environment_Season_Winter);
