#pragma once
#include "NativeGameplayTags.h"

/* ----------------------------- SLOT TYPE ---------------------------- */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_DEFAULT); // Generic slot, can contain any item
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_EQUIPMENT);     // Gear, weapons, tools, accessories, artifacts
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_CONSUMABLES);   // Food, potions, elixirs
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_FARMING);       // Harvested items: plants, crops, fruits, wood, etc.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_MINING);        // Mining resources: stone, ore, gems, etc.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_LEARNING);      // Tomes, scrolls, formulas, recipes, schematics (used to learn spells, abilities, crafting)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_PLACABLE);      // Items that can be placed in the world: beds, boxes, crafting stations, etc.
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_EXPLORATION);  // Maps, keys, letters, quest items
UE_DECLARE_GAMEPLAY_TAG_EXTERN(INVENTORY_SLOT_MISC);         // Everything else: crafting/alchemy/cooking materials that don't fit other categories

/* ----------------------------- ITEM TYPE ---------------------------- */
/* Equipment */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_EQUIPMENT);  // Gear, weapons, tools, accessories, artifacts
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_EQUIPMENT_GEAR);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_EQUIPMENT_WEAPON);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_EQUIPMENT_TOOL);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_EQUIPMENT_ACCESSORY);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_EQUIPMENT_ARTIFACT);

/* Consumables */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_CONSUMABLE); // Food, potions, elixirs
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_CONSUMABLE_FOOD);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_CONSUMABLE_POTION);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_CONSUMABLE_ELIXIR);

/* Farming */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_FARMING);   // Crops, fruits, vegetables, wood, harvested items
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_FARMING_PLANT);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_FARMING_WOOD);

/* Mining */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_MINING);    // Stone, ore, gems
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_MINING_STONE);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_MINING_ORE);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_MINING_GEM);

/* Learning */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_LEARNING);  // Tomes, scrolls, formulas, recipes, schematics
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_LEARNING_TOME);    // Learn abilities
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_LEARNING_SCROLL);  // Learn spells / words
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_LEARNING_FORMULA); // Learn potions/elixirs
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_LEARNING_RECIPE);  // Learn food/cooking
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_LEARNING_SCHEMATIC); // Learn crafting schematics

/* Placable */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_PLACABLE);  // Beds, boxes, crafting stations, furniture, etc.

/* Exploration */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_EXPLORATION); // Maps, keys, letters, quest items

/* Misc */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_TYPE_MISC);      // Crafting, alchemy, or other items that don’t fit above

/* ----------------------------- RARITY ---------------------------- */
/*ITEMIZATION.RARITY*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_RARITY_COMMON); // COMMON
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_RARITY_RARE); // RARE
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_RARITY_EPIC); // EPIC
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_RARITY_LEGENDARY); // LEGENDARY
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_RARITY_MYTHIC); // MYTHIC

/* ----------------------------- ACTION TYPE ---------------------------- */
/**ITEMIZATION.ActionType*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_ACTIONTYPE_INHAND); // The item can be used while in hand
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ITEMIZATION_ACTIONTYPE_ININVENTORY); // The item can be used from the inventory UI
