#include "MythicTags_Inventory.h"

/* ----------------------------- SLOT TYPE ---------------------------- */
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_DEFAULT, "Inventory.Slot.Default");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_EQUIPMENT, "Inventory.Slot.Equipment");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_CONSUMABLES, "Inventory.Slot.Consumables");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_FARMING, "Inventory.Slot.Farming");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_MINING, "Inventory.Slot.Mining");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_LEARNING, "Inventory.Slot.Learning");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_PLACABLE, "Inventory.Slot.Placable");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_EXPLORATION, "Inventory.Slot.Exploration");
UE_DEFINE_GAMEPLAY_TAG(INVENTORY_SLOT_MISC, "Inventory.Slot.Misc");

/* ----------------------------- ITEM TYPE ---------------------------- */
/* Equipment */
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_EQUIPMENT, "Itemization.Type.Equipment");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_EQUIPMENT_GEAR, "Itemization.Type.Equipment.Gear");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_EQUIPMENT_WEAPON, "Itemization.Type.Equipment.Weapon");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_EQUIPMENT_TOOL, "Itemization.Type.Equipment.Tool");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_EQUIPMENT_ACCESSORY, "Itemization.Type.Equipment.Accessory");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_EQUIPMENT_ARTIFACT, "Itemization.Type.Equipment.Artifact");

/* Consumables */
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_CONSUMABLE, "Itemization.Type.Consumable");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_CONSUMABLE_FOOD, "Itemization.Type.Consumable.Food");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_CONSUMABLE_POTION, "Itemization.Type.Consumable.Potion");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_CONSUMABLE_ELIXIR, "Itemization.Type.Consumable.Elixir");

/* Farming */
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_FARMING, "Itemization.Type.Farming");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_FARMING_PLANT, "Itemization.Type.Farming.Plant");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_FARMING_WOOD, "Itemization.Type.Farming.Wood");

/* Mining */
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_MINING, "Itemization.Type.Mining");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_MINING_STONE, "Itemization.Type.Mining.Stone");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_MINING_ORE, "Itemization.Type.Mining.Ore");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_MINING_GEM, "Itemization.Type.Mining.Gem");

/* Learning */
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_LEARNING, "Itemization.Type.Learning");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_LEARNING_TOME, "Itemization.Type.Learning.Tome");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_LEARNING_SCROLL, "Itemization.Type.Learning.Scroll");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_LEARNING_FORMULA, "Itemization.Type.Learning.Formula");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_LEARNING_RECIPE, "Itemization.Type.Learning.Recipe");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_LEARNING_SCHEMATIC, "Itemization.Type.Learning.Schematic");

/* Placable */
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_PLACABLE, "Itemization.Type.Placable");

/* Exploration */
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_EXPLORATION, "Itemization.Type.Exploration");

/* Misc */
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_TYPE_MISC, "Itemization.Type.Misc");

/* ----------------------------- RARITY ---------------------------- */
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_RARITY_COMMON, "Itemization.Rarity.Common");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_RARITY_RARE, "Itemization.Rarity.Rare");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_RARITY_EPIC, "Itemization.Rarity.Epic");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_RARITY_LEGENDARY, "Itemization.Rarity.Legendary");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_RARITY_MYTHIC, "Itemization.Rarity.Mythic");

/* ----------------------------- ACTION TYPE ---------------------------- */
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_ACTIONTYPE_INHAND, "Itemization.ActionType.InHand");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_ACTIONTYPE_INHAND_BEGIN, "Itemization.ActionType.InHand.Begin");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_ACTIONTYPE_INHAND_END, "Itemization.ActionType.InHand.End");
UE_DEFINE_GAMEPLAY_TAG(ITEMIZATION_ACTIONTYPE_ININVENTORY, "Itemization.ActionType.InInventory");
